language: node_js

node_js:
- '10'

cache:
  directories:
    - node_modules

install:
- yarn install

script:
- yarn lint
- yarn test

before_deploy:
- yarn build

deploy:
  provider: script
  script: netlify deploy -e production -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./public
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
  webhooks: https://www.travisbuddy.com
