language: node_js

node_js:
- '10'

sudo: true

cache:
  directories:
    - node_modules

install:
- yarn install

script:
- yarn lint
- yarn test

before_deploy:
- sudo apt install netlifyctl
- yarn build

deploy:
  provider: script
  script: ./scripts/deploy-draft.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
  webhooks: https://www.travisbuddy.com
