[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/new-member/*"
  to = "https://hedvig-web-onboarding-st-pr-43.herokuapp.com/new-member/:splat"
  status = 200

[[redirects]]
  from = "/new-member-assets/*"
  to = "https://hedvig-web-onboarding-st-pr-43.herokuapp.com/new-member-assets/:splat"
  status = 200
