backend:
  name: github
  repo: hedviginsurance/web
  branch: feature/netlify-cms

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: src/pages/about-us/index.md
        label: About Us
        name: about-us
        path: /about-us
        fields:
          - label: Path
            name: path
            widget: hidden
            default: /about-us
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Heading
            name: heading
            widget: string
          - label: Sections
            name: sections
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Paragraphs
                name: paragraphs
                widget: list
                field:
                  - label: Text
                    name: text
                    widget: text
      - file: src/pages/contact/index.md
        label: Contact
        path: /contact
        fields:
          - label: Path
            name: path
            widget: hidden
            default: /contact
          - label: Template Key
            name: templateKey
            widget: hidden
            default: contact-page
          - label: Title
            name: title
            widget: string
          - label: Heading
            name: heading
            widget: string
